# Generated by Django 4.1.6 on 2025-03-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('road_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_accidents', models.IntegerField()),
                ('total_fatalities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfirstna', models.CharField(blank=True, max_length=200, null=True)),
                ('plastna', models.CharField(blank=True, max_length=200, null=True)),
                ('pbadgeno', models.IntegerField(null=True)),
                ('pdesign', models.CharField(blank=True, max_length=200, null=True)),
                ('pjuri', models.CharField(blank=True, max_length=200, null=True)),
                ('pcontact', models.CharField(blank=True, max_length=200, null=True)),
                ('pdob', models.CharField(blank=True, max_length=200, null=True)),
                ('pgender', models.CharField(blank=True, max_length=200, null=True)),
                ('pPermanantAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('pTemporaryAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('pDistrict', models.CharField(blank=True, max_length=200, null=True)),
                ('pIDproof', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/')),
                ('pPhoto', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
