# Generated by Django 4.1.6 on 2025-03-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
