# Generated by Django 4.1.6 on 2025-03-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0002_authority_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='total_accidents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accident',
            name='total_fatalities',
            field=models.IntegerField(default=0),
        ),
    ]
